# Generated by Django 6.0.2 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="name",
        ),
        migrations.AddField(
            model_name="branch",
            name="address",
            field=models.CharField(default=1111111111111111111111111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_code",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="branch_name",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="email",
            field=models.EmailField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="branch",
            name="number",
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
