# Generated by Django 6.0.2 on 2026-06-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0002_remove_branch_name_branch_address_branch_branch_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("register_number", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="branch",
            name="area",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.areaoffice",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HeadOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hade_office_code", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("city", models.TextField()),
                ("state", models.TextField()),
                ("pincode", models.IntegerField()),
                ("address", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegionalOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.IntegerField()),
                (
                    "head_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.headoffice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="areaoffice",
            name="regional_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.regionaloffice",
            ),
        ),
    ]
