# Generated by Django 6.0.2 on 2026-06-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower_first_name", models.CharField(max_length=15)),
                ("borrower_last_name", models.CharField(max_length=15)),
                ("borrower_gender", models.CharField(max_length=15)),
                ("borrower_dob", models.DateField()),
                ("no_of_dependents", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("co_borrower_first_name", models.CharField(max_length=15)),
                ("co_borrower_last_name", models.CharField(max_length=15)),
                ("co_borrower_gender", models.CharField(max_length=15)),
                ("co_borrower_dob", models.DateField()),
                ("son_of", models.CharField(max_length=15)),
                ("relationship", models.CharField(max_length=15)),
                ("caste", models.CharField(max_length=15)),
                ("mobile_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pan_card_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/pan/"
                    ),
                ),
                (
                    "aadhaar_front_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/aadhaar/front/"
                    ),
                ),
                (
                    "aadhaar_back_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/aadhaar/back/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kyc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pan", models.CharField(max_length=8)),
                ("aadhar", models.IntegerField(max_length=12)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
