# Generated by Django 6.0.2 on 2026-06-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="accounts_number",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/accounts/"
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="account_no",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kyc",
            name="bank_name",
            field=models.CharField(default=1111111111111111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kyc",
            name="conform_account_number",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
