# Generated by Django 6.0.2 on 2026-06-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_document_accounts_number_kyc_account_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="aadhar",
            field=models.IntegerField(unique=True),
        ),
    ]
