# Generated by Django 6.0.2 on 2026-06-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group_Members",
        ),
    ]
