# Generated by Django 6.0.2 on 2026-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_delete_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="groups",
            name="meeting_day",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
