# Generated by Django 6.0.2 on 2026-06-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organizations",
            "0002_remove_branch_name_branch_address_branch_branch_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_number", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                (
                    "branch_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.branch",
                    ),
                ),
            ],
        ),
    ]
