# Generated by Django 6.0.2 on 2026-06-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0001_initial"),
        (
            "organizations",
            "0002_remove_branch_name_branch_address_branch_branch_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="branch_name",
        ),
        migrations.AddField(
            model_name="center",
            name="branch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centers",
                to="organizations.branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="center",
            name="center_number",
            field=models.PositiveIntegerField(),
        ),
    ]
